
print("what is your name")

name = input()
print(name)
print("what is your email")
email = input()
print(email)
print("what is your organization")
organization = input()
print(organization)
print("what is the access code")
access = input()
print("what is your issuer")
issuer = input()
print("+------------------------------------------+")
print("|APEX ENTERTAINMENT PASS                   |")
print("|------------------------------------------|")
print("| ATTENDEE :   " + name.ljust(12) + "                |")
print("| ORG      :   " + organization.ljust(12) + "                |")
print("| EMAIL    :   " + email.ljust(12) + "                |")
print("| ACCESS   :   " + access.ljust(12) + "                |")
print("| ISSUER   :   " + issuer.ljust(12) + "                |")
print("+------------------------------------------+")